## Chapter 12 of *R for Data Science* (2e, 2023)

In [1]:
from hea import data
from hea.tidy import col

In [2]:
flights = data("flights")

### 12.2

In [3]:
(
    flights.filter(
        (col("dep_time") > 600)
        & (col("dep_time") < 2000)
        & (abs(col("arr_delay")) < 20)
    )
)

shape: (172_286, 19)
┌──────┬───────┬─────┬──────────┬───┬──────────┬──────┬────────┬──────────────────────┐
│ year ┆ month ┆ day ┆ dep_time ┆ … ┆ distance ┆ hour ┆ minute ┆ time_hour            │
│ ---  ┆ ---   ┆ --- ┆ ---      ┆   ┆ ---      ┆ ---  ┆ ---    ┆ ---                  │
│ i64  ┆ i64   ┆ i64 ┆ f64      ┆   ┆ i64      ┆ i64  ┆ i64    ┆ str                  │
╞══════╪═══════╪═════╪══════════╪═══╪══════════╪══════╪════════╪══════════════════════╡
│ 2013 ┆ 1     ┆ 1   ┆ 601.0    ┆ … ┆ 1023     ┆ 6    ┆ 0      ┆ 2013-01-01T11:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ 602.0    ┆ … ┆ 1020     ┆ 6    ┆ 10     ┆ 2013-01-01T11:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ 602.0    ┆ … ┆ 502      ┆ 6    ┆ 5      ┆ 2013-01-01T11:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ 606.0    ┆ … ┆ 1085     ┆ 6    ┆ 10     ┆ 2013-01-01T11:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ 606.0    ┆ … ┆ 760      ┆ 6    ┆ 10     ┆ 2013-01-01T11:00:00Z │
│ …    ┆ …     ┆ …   ┆ …        ┆ … ┆ …        ┆ …    ┆ …      ┆ …                    │
│ 2013 ┆ 9     ┆ 30  ┆ 1955.0   ┆ … ┆ 762      ┆ 20   ┆ 0      ┆ 2013-10-01T00:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ 1955.0   ┆ … ┆ 589      ┆ 19   ┆ 35     ┆ 2013-09-30T23:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ 1955.0   ┆ … ┆ 1076     ┆ 19   ┆ 42     ┆ 2013-09-30T23:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ 1955.0   ┆ … ┆ 184      ┆ 20   ┆ 0      ┆ 2013-10-01T00:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ 1958.0   ┆ … ┆ 719      ┆ 20   ┆ 5      ┆ 2013-10-01T00:00:00Z │
└──────┴───────┴─────┴──────────┴───┴──────────┴──────┴────────┴──────────────────────┘

In [4]:
(
    flights.mutate(
        daytime=(col("dep_time") > 600) & (col("dep_time") < 2000),
        approx_ontime=abs(col("arr_delay")) < 20,
        _keep="used",
    )
)

shape: (336_776, 4)
┌──────────┬───────────┬─────────┬───────────────┐
│ dep_time ┆ arr_delay ┆ daytime ┆ approx_ontime │
│ ---      ┆ ---       ┆ ---     ┆ ---           │
│ f64      ┆ f64       ┆ bool    ┆ bool          │
╞══════════╪═══════════╪═════════╪═══════════════╡
│ 517.0    ┆ 11.0      ┆ false   ┆ true          │
│ 533.0    ┆ 20.0      ┆ false   ┆ false         │
│ 542.0    ┆ 33.0      ┆ false   ┆ false         │
│ 544.0    ┆ -18.0     ┆ false   ┆ true          │
│ 554.0    ┆ -25.0     ┆ false   ┆ false         │
│ …        ┆ …         ┆ …       ┆ …             │
│ null     ┆ null      ┆ null    ┆ null          │
│ null     ┆ null      ┆ null    ┆ null          │
│ null     ┆ null      ┆ null    ┆ null          │
│ null     ┆ null      ┆ null    ┆ null          │
│ null     ┆ null      ┆ null    ┆ null          │
└──────────┴───────────┴─────────┴───────────────┘

In [5]:
(
    flights.mutate(
        daytime=(col("dep_time") > 600) & (col("dep_time") < 2000),
        approx_ontime=abs(col("arr_delay")) < 20,
    ).filter(col("daytime") & col("approx_ontime"))
)

shape: (172_286, 21)
┌──────┬───────┬─────┬──────────┬───┬────────┬──────────────────────┬─────────┬───────────────┐
│ year ┆ month ┆ day ┆ dep_time ┆ … ┆ minute ┆ time_hour            ┆ daytime ┆ approx_ontime │
│ ---  ┆ ---   ┆ --- ┆ ---      ┆   ┆ ---    ┆ ---                  ┆ ---     ┆ ---           │
│ i64  ┆ i64   ┆ i64 ┆ f64      ┆   ┆ i64    ┆ str                  ┆ bool    ┆ bool          │
╞══════╪═══════╪═════╪══════════╪═══╪════════╪══════════════════════╪═════════╪═══════════════╡
│ 2013 ┆ 1     ┆ 1   ┆ 601.0    ┆ … ┆ 0      ┆ 2013-01-01T11:00:00Z ┆ true    ┆ true          │
│ 2013 ┆ 1     ┆ 1   ┆ 602.0    ┆ … ┆ 10     ┆ 2013-01-01T11:00:00Z ┆ true    ┆ true          │
│ 2013 ┆ 1     ┆ 1   ┆ 602.0    ┆ … ┆ 5      ┆ 2013-01-01T11:00:00Z ┆ true    ┆ true          │
│ 2013 ┆ 1     ┆ 1   ┆ 606.0    ┆ … ┆ 10     ┆ 2013-01-01T11:00:00Z ┆ true    ┆ true          │
│ 2013 ┆ 1     ┆ 1   ┆ 606.0    ┆ … ┆ 10     ┆ 2013-01-01T11:00:00Z ┆ true    ┆ true          │
│ …    ┆ …     ┆ …   ┆ …        ┆ … ┆ …      ┆ …                    ┆ …       ┆ …             │
│ 2013 ┆ 9     ┆ 30  ┆ 1955.0   ┆ … ┆ 0      ┆ 2013-10-01T00:00:00Z ┆ true    ┆ true          │
│ 2013 ┆ 9     ┆ 30  ┆ 1955.0   ┆ … ┆ 35     ┆ 2013-09-30T23:00:00Z ┆ true    ┆ true          │
│ 2013 ┆ 9     ┆ 30  ┆ 1955.0   ┆ … ┆ 42     ┆ 2013-09-30T23:00:00Z ┆ true    ┆ true          │
│ 2013 ┆ 9     ┆ 30  ┆ 1955.0   ┆ … ┆ 0      ┆ 2013-10-01T00:00:00Z ┆ true    ┆ true          │
│ 2013 ┆ 9     ┆ 30  ┆ 1958.0   ┆ … ┆ 5      ┆ 2013-10-01T00:00:00Z ┆ true    ┆ true          │
└──────┴───────┴─────┴──────────┴───┴────────┴──────────────────────┴─────────┴───────────────┘

In [6]:
flights.filter(col("dep_time").is_nan())

shape: (0, 19)
┌──────┬───────┬─────┬──────────┬───┬──────────┬──────┬────────┬───────────┐
│ year ┆ month ┆ day ┆ dep_time ┆ … ┆ distance ┆ hour ┆ minute ┆ time_hour │
│ ---  ┆ ---   ┆ --- ┆ ---      ┆   ┆ ---      ┆ ---  ┆ ---    ┆ ---       │
│ i64  ┆ i64   ┆ i64 ┆ f64      ┆   ┆ i64      ┆ i64  ┆ i64    ┆ str       │
╞══════╪═══════╪═════╪══════════╪═══╪══════════╪══════╪════════╪═══════════╡
└──────┴───────┴─────┴──────────┴───┴──────────┴──────┴────────┴───────────┘

In [7]:
flights.filter(col("dep_time").is_null())

shape: (8_255, 19)
┌──────┬───────┬─────┬──────────┬───┬──────────┬──────┬────────┬──────────────────────┐
│ year ┆ month ┆ day ┆ dep_time ┆ … ┆ distance ┆ hour ┆ minute ┆ time_hour            │
│ ---  ┆ ---   ┆ --- ┆ ---      ┆   ┆ ---      ┆ ---  ┆ ---    ┆ ---                  │
│ i64  ┆ i64   ┆ i64 ┆ f64      ┆   ┆ i64      ┆ i64  ┆ i64    ┆ str                  │
╞══════╪═══════╪═════╪══════════╪═══╪══════════╪══════╪════════╪══════════════════════╡
│ 2013 ┆ 1     ┆ 1   ┆ null     ┆ … ┆ 416      ┆ 16   ┆ 30     ┆ 2013-01-01T21:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ null     ┆ … ┆ 1389     ┆ 19   ┆ 35     ┆ 2013-01-02T00:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ null     ┆ … ┆ 1096     ┆ 15   ┆ 0      ┆ 2013-01-01T20:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ null     ┆ … ┆ 1069     ┆ 6    ┆ 0      ┆ 2013-01-01T11:00:00Z │
│ 2013 ┆ 1     ┆ 2   ┆ null     ┆ … ┆ 569      ┆ 15   ┆ 40     ┆ 2013-01-02T20:00:00Z │
│ …    ┆ …     ┆ …   ┆ …        ┆ … ┆ …        ┆ …    ┆ …      ┆ …                    │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 213      ┆ 14   ┆ 55     ┆ 2013-09-30T18:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 198      ┆ 22   ┆ 0      ┆ 2013-10-01T02:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 764      ┆ 12   ┆ 10     ┆ 2013-09-30T16:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 419      ┆ 11   ┆ 59     ┆ 2013-09-30T15:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 431      ┆ 8    ┆ 40     ┆ 2013-09-30T12:00:00Z │
└──────┴───────┴─────┴──────────┴───┴──────────┴──────┴────────┴──────────────────────┘

In [8]:
from hea import session_info

session_info()

Python version 3.13.11 (CPython)
Platform: arm64-darwin25.4.0
Running under: macOS 26.4.1

BLAS:   accelerate
LAPACK: accelerate

locale: C.UTF-8

time zone: CEST

hea version 0.1.3

attached packages:
[1] IPython_9.13.0    hea_0.1.3         matplotlib_3.10.9 numpy_2.4.4
[5] pandas_3.0.2      polars_1.40.1     pyarrow_24.0.0    pytest_9.0.3
[9] scipy_1.17.1

loaded via a namespace (and not attached):
 [1] PIL_12.2.0            appnope_0.1.4         argparse_1.1
 [4] asttokens_3.0.1       comm_0.2.3            csv_1.0
 [7] ctypes_1.1.0          cycler_0.12.1         dateutil_2.9.0.post0
[10] debugpy_1.8.20        decimal_1.70          decorator_5.2.1
[13] defusedxml_0.7.1      executing_2.2.1       ipaddress_1.0
[16] ipykernel_7.2.0       jedi_0.19.2           json_2.0.9
[19] jupyter_client_8.8.0  jupyter_core_5.9.1    kiwisolver_1.5.0
[22] logging_0.5.1.2       packaging_26.2        parso_0.8.6
[25] platform_1.0.8        platformdirs_4.9.6    prompt_toolkit_3.0.52
[28] psutil_7.2.2          pure_eval_0.2.3       pydevd_3.2.3
[31] pygments_2.20.0       pyparsing_3.3.2       rdatasets_0.2.10
[34] re_2.2.1              six_1.17.0            sksparse_0.5.0
[37] socketserver_0.4      stack_data_0.6.3      tornado_6.5.5
[40] traitlets_5.14.3      wcwidth_0.6.0         zlib_1.0
[43] zmq_27.1.0