## Chapter 19 of *R for Data Science* (2e, 2023)

In [1]:
from hea import data

### 19.2

In [2]:
flights = data("flights")
flights

shape: (336_776, 19)
┌──────┬───────┬─────┬──────────┬───┬──────────┬──────┬────────┬──────────────────────┐
│ year ┆ month ┆ day ┆ dep_time ┆ … ┆ distance ┆ hour ┆ minute ┆ time_hour            │
│ ---  ┆ ---   ┆ --- ┆ ---      ┆   ┆ ---      ┆ ---  ┆ ---    ┆ ---                  │
│ i64  ┆ i64   ┆ i64 ┆ f64      ┆   ┆ i64      ┆ i64  ┆ i64    ┆ str                  │
╞══════╪═══════╪═════╪══════════╪═══╪══════════╪══════╪════════╪══════════════════════╡
│ 2013 ┆ 1     ┆ 1   ┆ 517.0    ┆ … ┆ 1400     ┆ 5    ┆ 15     ┆ 2013-01-01T10:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ 533.0    ┆ … ┆ 1416     ┆ 5    ┆ 29     ┆ 2013-01-01T10:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ 542.0    ┆ … ┆ 1089     ┆ 5    ┆ 40     ┆ 2013-01-01T10:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ 544.0    ┆ … ┆ 1576     ┆ 5    ┆ 45     ┆ 2013-01-01T10:00:00Z │
│ 2013 ┆ 1     ┆ 1   ┆ 554.0    ┆ … ┆ 762      ┆ 6    ┆ 0      ┆ 2013-01-01T11:00:00Z │
│ …    ┆ …     ┆ …   ┆ …        ┆ … ┆ …        ┆ …    ┆ …      ┆ …                    │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 213      ┆ 14   ┆ 55     ┆ 2013-09-30T18:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 198      ┆ 22   ┆ 0      ┆ 2013-10-01T02:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 764      ┆ 12   ┆ 10     ┆ 2013-09-30T16:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 419      ┆ 11   ┆ 59     ┆ 2013-09-30T15:00:00Z │
│ 2013 ┆ 9     ┆ 30  ┆ null     ┆ … ┆ 431      ┆ 8    ┆ 40     ┆ 2013-09-30T12:00:00Z │
└──────┴───────┴─────┴──────────┴───┴──────────┴──────┴────────┴──────────────────────┘

In [3]:
airlines = data("airlines")
airlines

shape: (16, 2)
┌─────────┬────────────────────────┐
│ carrier ┆ name                   │
│ ---     ┆ ---                    │
│ str     ┆ str                    │
╞═════════╪════════════════════════╡
│ 9E      ┆ Endeavor Air Inc.      │
│ AA      ┆ American Airlines Inc. │
│ AS      ┆ Alaska Airlines Inc.   │
│ B6      ┆ JetBlue Airways        │
│ DL      ┆ Delta Air Lines Inc.   │
│ …       ┆ …                      │
│ UA      ┆ United Air Lines Inc.  │
│ US      ┆ US Airways Inc.        │
│ VX      ┆ Virgin America         │
│ WN      ┆ Southwest Airlines Co. │
│ YV      ┆ Mesa Airlines Inc.     │
└─────────┴────────────────────────┘

In [4]:
airports = data("airports")
airports

shape: (1_458, 8)
┌─────┬────────────────────────────┬───────────┬─────────────┬──────┬─────┬─────┬──────────────────┐
│ faa ┆ name                       ┆ lat       ┆ lon         ┆ alt  ┆ tz  ┆ dst ┆ tzone            │
│ --- ┆ ---                        ┆ ---       ┆ ---         ┆ ---  ┆ --- ┆ --- ┆ ---              │
│ str ┆ str                        ┆ f64       ┆ f64         ┆ i64  ┆ i64 ┆ str ┆ str              │
╞═════╪════════════════════════════╪═══════════╪═════════════╪══════╪═════╪═════╪══════════════════╡
│ 04G ┆ Lansdowne Airport          ┆ 41.130472 ┆ -80.619583  ┆ 1044 ┆ -5  ┆ A   ┆ America/New_York │
│ 06A ┆ Moton Field Municipal      ┆ 32.460572 ┆ -85.680028  ┆ 264  ┆ -6  ┆ A   ┆ America/Chicago  │
│     ┆ Airport                    ┆           ┆             ┆      ┆     ┆     ┆                  │
│ 06C ┆ Schaumburg Regional        ┆ 41.989341 ┆ -88.101243  ┆ 801  ┆ -6  ┆ A   ┆ America/Chicago  │
│ 06N ┆ Randall Airport            ┆ 41.431912 ┆ -74.391561  ┆ 523  ┆ -5  ┆ A   ┆ America/New_York │
│ 09J ┆ Jekyll Island Airport      ┆ 31.074472 ┆ -81.427778  ┆ 11   ┆ -5  ┆ A   ┆ America/New_York │
│ …   ┆ …                          ┆ …         ┆ …           ┆ …    ┆ …   ┆ …   ┆ …                │
│ ZUN ┆ Black Rock                 ┆ 35.083228 ┆ -108.791778 ┆ 6454 ┆ -7  ┆ A   ┆ America/Denver   │
│ ZVE ┆ New Haven Rail Station     ┆ 41.298669 ┆ -72.925992  ┆ 7    ┆ -5  ┆ A   ┆ America/New_York │
│ ZWI ┆ Wilmington Amtrak Station  ┆ 39.736667 ┆ -75.551667  ┆ 0    ┆ -5  ┆ A   ┆ America/New_York │
│ ZWU ┆ Washington Union Station   ┆ 38.89746  ┆ -77.00643   ┆ 76   ┆ -5  ┆ A   ┆ America/New_York │
│ ZYP ┆ Penn Station               ┆ 40.7505   ┆ -73.9935    ┆ 35   ┆ -5  ┆ A   ┆ America/New_York │
└─────┴────────────────────────────┴───────────┴─────────────┴──────┴─────┴─────┴──────────────────┘

In [5]:
planes = data('planes')
planes

shape: (3_322, 9)
┌─────────┬────────┬──────────────────┬──────────────────┬───┬─────────┬───────┬───────┬───────────┐
│ tailnum ┆ year   ┆ type             ┆ manufacturer     ┆ … ┆ engines ┆ seats ┆ speed ┆ engine    │
│ ---     ┆ ---    ┆ ---              ┆ ---              ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---       │
│ str     ┆ f64    ┆ str              ┆ str              ┆   ┆ i64     ┆ i64   ┆ f64   ┆ str       │
╞═════════╪════════╪══════════════════╪══════════════════╪═══╪═════════╪═══════╪═══════╪═══════════╡
│ N10156  ┆ 2004.0 ┆ Fixed wing multi ┆ EMBRAER          ┆ … ┆ 2       ┆ 55    ┆ null  ┆ Turbo-fan │
│         ┆        ┆ engine           ┆                  ┆   ┆         ┆       ┆       ┆           │
│ N102UW  ┆ 1998.0 ┆ Fixed wing multi ┆ AIRBUS INDUSTRIE ┆ … ┆ 2       ┆ 182   ┆ null  ┆ Turbo-fan │
│         ┆        ┆ engine           ┆                  ┆   ┆         ┆       ┆       ┆           │
│ N103US  ┆ 1999.0 ┆ Fixed wing multi ┆ AIRBUS INDUSTRIE ┆ … ┆ 2       ┆ 182   ┆ null  ┆ Turbo-fan │
│         ┆        ┆ engine           ┆                  ┆   ┆         ┆       ┆       ┆           │
│ N104UW  ┆ 1999.0 ┆ Fixed wing multi ┆ AIRBUS INDUSTRIE ┆ … ┆ 2       ┆ 182   ┆ null  ┆ Turbo-fan │
│         ┆        ┆ engine           ┆                  ┆   ┆         ┆       ┆       ┆           │
│ N10575  ┆ 2002.0 ┆ Fixed wing multi ┆ EMBRAER          ┆ … ┆ 2       ┆ 55    ┆ null  ┆ Turbo-fan │
│         ┆        ┆ engine           ┆                  ┆   ┆         ┆       ┆       ┆           │
│ …       ┆ …      ┆ …                ┆ …                ┆ … ┆ …       ┆ …     ┆ …     ┆ …         │
│ N997AT  ┆ 2002.0 ┆ Fixed wing multi ┆ BOEING           ┆ … ┆ 2       ┆ 100   ┆ null  ┆ Turbo-fan │
│         ┆        ┆ engine           ┆                  ┆   ┆         ┆       ┆       ┆           │
│ N997DL  ┆ 1992.0 ┆ Fixed wing multi ┆ MCDONNELL        ┆ … ┆ 2       ┆ 142   ┆ null  ┆ Turbo-fan │
│         ┆        ┆ engine           ┆ DOUGLAS AIRCRAFT ┆   ┆         ┆       ┆       ┆           │
│         ┆        ┆                  ┆ CO               ┆   ┆         ┆       ┆       ┆           │
│ N998AT  ┆ 2002.0 ┆ Fixed wing multi ┆ BOEING           ┆ … ┆ 2       ┆ 100   ┆ null  ┆ Turbo-fan │
│         ┆        ┆ engine           ┆                  ┆   ┆         ┆       ┆       ┆           │
│ N998DL  ┆ 1992.0 ┆ Fixed wing multi ┆ MCDONNELL        ┆ … ┆ 2       ┆ 142   ┆ null  ┆ Turbo-jet │
│         ┆        ┆ engine           ┆ DOUGLAS          ┆   ┆         ┆       ┆       ┆           │
│         ┆        ┆                  ┆ CORPORATION      ┆   ┆         ┆       ┆       ┆           │
│ N999DN  ┆ 1992.0 ┆ Fixed wing multi ┆ MCDONNELL        ┆ … ┆ 2       ┆ 142   ┆ null  ┆ Turbo-jet │
│         ┆        ┆ engine           ┆ DOUGLAS          ┆   ┆         ┆       ┆       ┆           │
│         ┆        ┆                  ┆ CORPORATION      ┆   ┆         ┆       ┆       ┆           │
└─────────┴────────┴──────────────────┴──────────────────┴───┴─────────┴───────┴───────┴───────────┘

In [6]:
weather = data("weather")
weather

shape: (26_115, 15)
┌────────┬──────┬───────┬─────┬───┬────────┬──────────┬───────┬──────────────────────┐
│ origin ┆ year ┆ month ┆ day ┆ … ┆ precip ┆ pressure ┆ visib ┆ time_hour            │
│ ---    ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---    ┆ ---      ┆ ---   ┆ ---                  │
│ str    ┆ i64  ┆ i64   ┆ i64 ┆   ┆ f64    ┆ f64      ┆ f64   ┆ str                  │
╞════════╪══════╪═══════╪═════╪═══╪════════╪══════════╪═══════╪══════════════════════╡
│ EWR    ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 0.0    ┆ 1012.0   ┆ 10.0  ┆ 2013-01-01T06:00:00Z │
│ EWR    ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 0.0    ┆ 1012.3   ┆ 10.0  ┆ 2013-01-01T07:00:00Z │
│ EWR    ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 0.0    ┆ 1012.5   ┆ 10.0  ┆ 2013-01-01T08:00:00Z │
│ EWR    ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 0.0    ┆ 1012.2   ┆ 10.0  ┆ 2013-01-01T09:00:00Z │
│ EWR    ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 0.0    ┆ 1011.9   ┆ 10.0  ┆ 2013-01-01T10:00:00Z │
│ …      ┆ …    ┆ …     ┆ …   ┆ … ┆ …      ┆ …        ┆ …     ┆ …                    │
│ LGA    ┆ 2013 ┆ 12    ┆ 30  ┆ … ┆ 0.0    ┆ 1017.1   ┆ 10.0  ┆ 2013-12-30T19:00:00Z │
│ LGA    ┆ 2013 ┆ 12    ┆ 30  ┆ … ┆ 0.0    ┆ 1018.8   ┆ 10.0  ┆ 2013-12-30T20:00:00Z │
│ LGA    ┆ 2013 ┆ 12    ┆ 30  ┆ … ┆ 0.0    ┆ 1019.5   ┆ 10.0  ┆ 2013-12-30T21:00:00Z │
│ LGA    ┆ 2013 ┆ 12    ┆ 30  ┆ … ┆ 0.0    ┆ 1019.9   ┆ 10.0  ┆ 2013-12-30T22:00:00Z │
│ LGA    ┆ 2013 ┆ 12    ┆ 30  ┆ … ┆ 0.0    ┆ 1020.9   ┆ 10.0  ┆ 2013-12-30T23:00:00Z │
└────────┴──────┴───────┴─────┴───┴────────┴──────────┴───────┴──────────────────────┘

In [7]:
from hea.tidy import col
planes.count("tailnum").filter(col("n") > 1)

shape: (0, 2)
┌─────────┬─────┐
│ tailnum ┆ n   │
│ ---     ┆ --- │
│ str     ┆ u32 │
╞═════════╪═════╡
└─────────┴─────┘

In [8]:
weather.count("time_hour", "origin").filter(col("n") > 1)

shape: (0, 3)
┌───────────┬────────┬─────┐
│ time_hour ┆ origin ┆ n   │
│ ---       ┆ ---    ┆ --- │
│ str       ┆ str    ┆ u32 │
╞═══════════╪════════╪═════╡
└───────────┴────────┴─────┘

In [9]:
planes.filter(col("tailnum").is_null())

shape: (0, 9)
┌─────────┬──────┬──────┬──────────────┬───┬─────────┬───────┬───────┬────────┐
│ tailnum ┆ year ┆ type ┆ manufacturer ┆ … ┆ engines ┆ seats ┆ speed ┆ engine │
│ ---     ┆ ---  ┆ ---  ┆ ---          ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---    │
│ str     ┆ f64  ┆ str  ┆ str          ┆   ┆ i64     ┆ i64   ┆ f64   ┆ str    │
╞═════════╪══════╪══════╪══════════════╪═══╪═════════╪═══════╪═══════╪════════╡
└─────────┴──────┴──────┴──────────────┴───┴─────────┴───────┴───────┴────────┘

In [10]:
weather.filter(col("time_hour").is_null() | col("origin").is_null())

shape: (0, 15)
┌────────┬──────┬───────┬─────┬───┬────────┬──────────┬───────┬───────────┐
│ origin ┆ year ┆ month ┆ day ┆ … ┆ precip ┆ pressure ┆ visib ┆ time_hour │
│ ---    ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---    ┆ ---      ┆ ---   ┆ ---       │
│ str    ┆ i64  ┆ i64   ┆ i64 ┆   ┆ f64    ┆ f64      ┆ f64   ┆ str       │
╞════════╪══════╪═══════╪═════╪═══╪════════╪══════════╪═══════╪═══════════╡
└────────┴──────┴───────┴─────┴───┴────────┴──────────┴───────┴───────────┘

In [11]:
flights.count("time_hour", "carrier", "flight").filter(col("n") > 1)

shape: (0, 4)
┌───────────┬─────────┬────────┬─────┐
│ time_hour ┆ carrier ┆ flight ┆ n   │
│ ---       ┆ ---     ┆ ---    ┆ --- │
│ str       ┆ str     ┆ i64    ┆ u32 │
╞═══════════╪═════════╪════════╪═════╡
└───────────┴─────────┴────────┴─────┘

In [12]:
airports.count("alt", "lat").filter(col("n") > 1)

shape: (1, 3)
┌─────┬───────────┬─────┐
│ alt ┆ lat       ┆ n   │
│ --- ┆ ---       ┆ --- │
│ i64 ┆ f64       ┆ u32 │
╞═════╪═══════════╪═════╡
│ 13  ┆ 40.639751 ┆ 2   │
└─────┴───────────┴─────┘

In [13]:
from hea.tidy import row_number
flights2 = flights.mutate(id=row_number(), _before=1)
flights2

shape: (336_776, 20)
┌────────┬──────┬───────┬─────┬───┬──────────┬──────┬────────┬──────────────────────┐
│ id     ┆ year ┆ month ┆ day ┆ … ┆ distance ┆ hour ┆ minute ┆ time_hour            │
│ ---    ┆ ---  ┆ ---   ┆ --- ┆   ┆ ---      ┆ ---  ┆ ---    ┆ ---                  │
│ i64    ┆ i64  ┆ i64   ┆ i64 ┆   ┆ i64      ┆ i64  ┆ i64    ┆ str                  │
╞════════╪══════╪═══════╪═════╪═══╪══════════╪══════╪════════╪══════════════════════╡
│ 1      ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 1400     ┆ 5    ┆ 15     ┆ 2013-01-01T10:00:00Z │
│ 2      ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 1416     ┆ 5    ┆ 29     ┆ 2013-01-01T10:00:00Z │
│ 3      ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 1089     ┆ 5    ┆ 40     ┆ 2013-01-01T10:00:00Z │
│ 4      ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 1576     ┆ 5    ┆ 45     ┆ 2013-01-01T10:00:00Z │
│ 5      ┆ 2013 ┆ 1     ┆ 1   ┆ … ┆ 762      ┆ 6    ┆ 0      ┆ 2013-01-01T11:00:00Z │
│ …      ┆ …    ┆ …     ┆ …   ┆ … ┆ …        ┆ …    ┆ …      ┆ …                    │
│ 336772 ┆ 2013 ┆ 9     ┆ 30  ┆ … ┆ 213      ┆ 14   ┆ 55     ┆ 2013-09-30T18:00:00Z │
│ 336773 ┆ 2013 ┆ 9     ┆ 30  ┆ … ┆ 198      ┆ 22   ┆ 0      ┆ 2013-10-01T02:00:00Z │
│ 336774 ┆ 2013 ┆ 9     ┆ 30  ┆ … ┆ 764      ┆ 12   ┆ 10     ┆ 2013-09-30T16:00:00Z │
│ 336775 ┆ 2013 ┆ 9     ┆ 30  ┆ … ┆ 419      ┆ 11   ┆ 59     ┆ 2013-09-30T15:00:00Z │
│ 336776 ┆ 2013 ┆ 9     ┆ 30  ┆ … ┆ 431      ┆ 8    ┆ 40     ┆ 2013-09-30T12:00:00Z │
└────────┴──────┴───────┴─────┴───┴──────────┴──────┴────────┴──────────────────────┘

### 19.3

In [14]:
flights2 = flights.select("year", "time_hour", "origin", "dest", "tailnum", "carrier")
flights2

shape: (336_776, 6)
┌──────┬──────────────────────┬────────┬──────┬─────────┬─────────┐
│ year ┆ time_hour            ┆ origin ┆ dest ┆ tailnum ┆ carrier │
│ ---  ┆ ---                  ┆ ---    ┆ ---  ┆ ---     ┆ ---     │
│ i64  ┆ str                  ┆ str    ┆ str  ┆ str     ┆ str     │
╞══════╪══════════════════════╪════════╪══════╪═════════╪═════════╡
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ EWR    ┆ IAH  ┆ N14228  ┆ UA      │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ LGA    ┆ IAH  ┆ N24211  ┆ UA      │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ MIA  ┆ N619AA  ┆ AA      │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ BQN  ┆ N804JB  ┆ B6      │
│ 2013 ┆ 2013-01-01T11:00:00Z ┆ LGA    ┆ ATL  ┆ N668DN  ┆ DL      │
│ …    ┆ …                    ┆ …      ┆ …    ┆ …       ┆ …       │
│ 2013 ┆ 2013-09-30T18:00:00Z ┆ JFK    ┆ DCA  ┆ null    ┆ 9E      │
│ 2013 ┆ 2013-10-01T02:00:00Z ┆ LGA    ┆ SYR  ┆ null    ┆ 9E      │
│ 2013 ┆ 2013-09-30T16:00:00Z ┆ LGA    ┆ BNA  ┆ N535MQ  ┆ MQ      │
│ 2013 ┆ 2013-09-30T15:00:00Z ┆ LGA    ┆ CLE  ┆ N511MQ  ┆ MQ      │
│ 2013 ┆ 2013-09-30T12:00:00Z ┆ LGA    ┆ RDU  ┆ N839MQ  ┆ MQ      │
└──────┴──────────────────────┴────────┴──────┴─────────┴─────────┘

In [15]:
flights2.left_join(airlines)

Joining with `by = join_by('carrier')`

shape: (336_776, 7)
┌──────┬──────────────────────┬────────┬──────┬─────────┬─────────┬────────────────────────┐
│ year ┆ time_hour            ┆ origin ┆ dest ┆ tailnum ┆ carrier ┆ name                   │
│ ---  ┆ ---                  ┆ ---    ┆ ---  ┆ ---     ┆ ---     ┆ ---                    │
│ i64  ┆ str                  ┆ str    ┆ str  ┆ str     ┆ str     ┆ str                    │
╞══════╪══════════════════════╪════════╪══════╪═════════╪═════════╪════════════════════════╡
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ EWR    ┆ IAH  ┆ N14228  ┆ UA      ┆ United Air Lines Inc.  │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ LGA    ┆ IAH  ┆ N24211  ┆ UA      ┆ United Air Lines Inc.  │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ MIA  ┆ N619AA  ┆ AA      ┆ American Airlines Inc. │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ BQN  ┆ N804JB  ┆ B6      ┆ JetBlue Airways        │
│ 2013 ┆ 2013-01-01T11:00:00Z ┆ LGA    ┆ ATL  ┆ N668DN  ┆ DL      ┆ Delta Air Lines Inc.   │
│ …    ┆ …                    ┆ …      ┆ …    ┆ …       ┆ …       ┆ …                      │
│ 2013 ┆ 2013-09-30T18:00:00Z ┆ JFK    ┆ DCA  ┆ null    ┆ 9E      ┆ Endeavor Air Inc.      │
│ 2013 ┆ 2013-10-01T02:00:00Z ┆ LGA    ┆ SYR  ┆ null    ┆ 9E      ┆ Endeavor Air Inc.      │
│ 2013 ┆ 2013-09-30T16:00:00Z ┆ LGA    ┆ BNA  ┆ N535MQ  ┆ MQ      ┆ Envoy Air              │
│ 2013 ┆ 2013-09-30T15:00:00Z ┆ LGA    ┆ CLE  ┆ N511MQ  ┆ MQ      ┆ Envoy Air              │
│ 2013 ┆ 2013-09-30T12:00:00Z ┆ LGA    ┆ RDU  ┆ N839MQ  ┆ MQ      ┆ Envoy Air              │
└──────┴──────────────────────┴────────┴──────┴─────────┴─────────┴────────────────────────┘

In [16]:
flights2.left_join(
    weather.select("origin", "time_hour", "temp", "wind_speed")
)

Joining with `by = join_by('time_hour', 'origin')`

shape: (336_776, 8)
┌──────┬──────────────────────┬────────┬──────┬─────────┬─────────┬───────┬────────────┐
│ year ┆ time_hour            ┆ origin ┆ dest ┆ tailnum ┆ carrier ┆ temp  ┆ wind_speed │
│ ---  ┆ ---                  ┆ ---    ┆ ---  ┆ ---     ┆ ---     ┆ ---   ┆ ---        │
│ i64  ┆ str                  ┆ str    ┆ str  ┆ str     ┆ str     ┆ f64   ┆ f64        │
╞══════╪══════════════════════╪════════╪══════╪═════════╪═════════╪═══════╪════════════╡
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ EWR    ┆ IAH  ┆ N14228  ┆ UA      ┆ 39.02 ┆ 12.65858   │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ LGA    ┆ IAH  ┆ N24211  ┆ UA      ┆ 39.92 ┆ 14.96014   │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ MIA  ┆ N619AA  ┆ AA      ┆ 39.02 ┆ 14.96014   │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ BQN  ┆ N804JB  ┆ B6      ┆ 39.02 ┆ 14.96014   │
│ 2013 ┆ 2013-01-01T11:00:00Z ┆ LGA    ┆ ATL  ┆ N668DN  ┆ DL      ┆ 39.92 ┆ 16.11092   │
│ …    ┆ …                    ┆ …      ┆ …    ┆ …       ┆ …       ┆ …     ┆ …          │
│ 2013 ┆ 2013-09-30T18:00:00Z ┆ JFK    ┆ DCA  ┆ null    ┆ 9E      ┆ 68.0  ┆ 11.5078    │
│ 2013 ┆ 2013-10-01T02:00:00Z ┆ LGA    ┆ SYR  ┆ null    ┆ 9E      ┆ 64.94 ┆ 6.90468    │
│ 2013 ┆ 2013-09-30T16:00:00Z ┆ LGA    ┆ BNA  ┆ N535MQ  ┆ MQ      ┆ 69.08 ┆ 5.7539     │
│ 2013 ┆ 2013-09-30T15:00:00Z ┆ LGA    ┆ CLE  ┆ N511MQ  ┆ MQ      ┆ 66.92 ┆ 8.05546    │
│ 2013 ┆ 2013-09-30T12:00:00Z ┆ LGA    ┆ RDU  ┆ N839MQ  ┆ MQ      ┆ 60.98 ┆ 5.7539     │
└──────┴──────────────────────┴────────┴──────┴─────────┴─────────┴───────┴────────────┘

In [17]:
flights2.left_join(
    planes.select("tailnum", "type", "engines", "seats")
)

Joining with `by = join_by('tailnum')`

shape: (336_776, 9)
┌──────┬────────────────────────┬────────┬──────┬───┬─────────┬──────────────────┬─────────┬───────┐
│ year ┆ time_hour              ┆ origin ┆ dest ┆ … ┆ carrier ┆ type             ┆ engines ┆ seats │
│ ---  ┆ ---                    ┆ ---    ┆ ---  ┆   ┆ ---     ┆ ---              ┆ ---     ┆ ---   │
│ i64  ┆ str                    ┆ str    ┆ str  ┆   ┆ str     ┆ str              ┆ i64     ┆ i64   │
╞══════╪════════════════════════╪════════╪══════╪═══╪═════════╪══════════════════╪═════════╪═══════╡
│ 2013 ┆ 2013-01-01T10:00:00Z   ┆ EWR    ┆ IAH  ┆ … ┆ UA      ┆ Fixed wing multi ┆ 2       ┆ 149   │
│      ┆                        ┆        ┆      ┆   ┆         ┆ engine           ┆         ┆       │
│ 2013 ┆ 2013-01-01T10:00:00Z   ┆ LGA    ┆ IAH  ┆ … ┆ UA      ┆ Fixed wing multi ┆ 2       ┆ 149   │
│      ┆                        ┆        ┆      ┆   ┆         ┆ engine           ┆         ┆       │
│ 2013 ┆ 2013-01-01T10:00:00Z   ┆ JFK    ┆ MIA  ┆ … ┆ AA      ┆ Fixed wing multi ┆ 2       ┆ 178   │
│      ┆                        ┆        ┆      ┆   ┆         ┆ engine           ┆         ┆       │
│ 2013 ┆ 2013-01-01T10:00:00Z   ┆ JFK    ┆ BQN  ┆ … ┆ B6      ┆ Fixed wing multi ┆ 2       ┆ 200   │
│      ┆                        ┆        ┆      ┆   ┆         ┆ engine           ┆         ┆       │
│ 2013 ┆ 2013-01-01T11:00:00Z   ┆ LGA    ┆ ATL  ┆ … ┆ DL      ┆ Fixed wing multi ┆ 2       ┆ 178   │
│      ┆                        ┆        ┆      ┆   ┆         ┆ engine           ┆         ┆       │
│ …    ┆ …                      ┆ …      ┆ …    ┆ … ┆ …       ┆ …                ┆ …       ┆ …     │
│ 2013 ┆ 2013-09-30T18:00:00Z   ┆ JFK    ┆ DCA  ┆ … ┆ 9E      ┆ null             ┆ null    ┆ null  │
│ 2013 ┆ 2013-10-01T02:00:00Z   ┆ LGA    ┆ SYR  ┆ … ┆ 9E      ┆ null             ┆ null    ┆ null  │
│ 2013 ┆ 2013-09-30T16:00:00Z   ┆ LGA    ┆ BNA  ┆ … ┆ MQ      ┆ null             ┆ null    ┆ null  │
│ 2013 ┆ 2013-09-30T15:00:00Z   ┆ LGA    ┆ CLE  ┆ … ┆ MQ      ┆ null             ┆ null    ┆ null  │
│ 2013 ┆ 2013-09-30T12:00:00Z   ┆ LGA    ┆ RDU  ┆ … ┆ MQ      ┆ null             ┆ null    ┆ null  │
└──────┴────────────────────────┴────────┴──────┴───┴─────────┴──────────────────┴─────────┴───────┘

In [18]:
flights2.filter(col("tailnum") == "N3ALAA").left_join(
    planes.select("tailnum", "type", "engines", "seats")
)

Joining with `by = join_by('tailnum')`

shape: (63, 9)
┌──────┬──────────────────────┬────────┬──────┬───┬─────────┬──────┬─────────┬───────┐
│ year ┆ time_hour            ┆ origin ┆ dest ┆ … ┆ carrier ┆ type ┆ engines ┆ seats │
│ ---  ┆ ---                  ┆ ---    ┆ ---  ┆   ┆ ---     ┆ ---  ┆ ---     ┆ ---   │
│ i64  ┆ str                  ┆ str    ┆ str  ┆   ┆ str     ┆ str  ┆ i64     ┆ i64   │
╞══════╪══════════════════════╪════════╪══════╪═══╪═════════╪══════╪═════════╪═══════╡
│ 2013 ┆ 2013-01-01T11:00:00Z ┆ LGA    ┆ ORD  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ 2013 ┆ 2013-01-02T23:00:00Z ┆ LGA    ┆ ORD  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ 2013 ┆ 2013-01-03T11:00:00Z ┆ LGA    ┆ ORD  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ 2013 ┆ 2013-01-08T00:00:00Z ┆ LGA    ┆ ORD  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ 2013 ┆ 2013-01-08T22:00:00Z ┆ JFK    ┆ ORD  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ …    ┆ …                    ┆ …      ┆ …    ┆ … ┆ …       ┆ …    ┆ …       ┆ …     │
│ 2013 ┆ 2013-07-28T20:00:00Z ┆ JFK    ┆ DFW  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ 2013 ┆ 2013-08-27T17:00:00Z ┆ LGA    ┆ DFW  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ 2013 ┆ 2013-09-09T15:00:00Z ┆ LGA    ┆ ORD  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ 2013 ┆ 2013-09-16T21:00:00Z ┆ JFK    ┆ SAN  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
│ 2013 ┆ 2013-09-22T10:00:00Z ┆ EWR    ┆ MIA  ┆ … ┆ AA      ┆ null ┆ null    ┆ null  │
└──────┴──────────────────────┴────────┴──────┴───┴─────────┴──────┴─────────┴───────┘

In [19]:
flights2.left_join(planes)

Joining with `by = join_by('year', 'tailnum')`

shape: (336_776, 13)
┌────────┬──────────────────────┬────────┬──────┬───┬─────────┬───────┬───────┬────────┐
│ year   ┆ time_hour            ┆ origin ┆ dest ┆ … ┆ engines ┆ seats ┆ speed ┆ engine │
│ ---    ┆ ---                  ┆ ---    ┆ ---  ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---    │
│ f64    ┆ str                  ┆ str    ┆ str  ┆   ┆ i64     ┆ i64   ┆ f64   ┆ str    │
╞════════╪══════════════════════╪════════╪══════╪═══╪═════════╪═══════╪═══════╪════════╡
│ 2013.0 ┆ 2013-01-01T10:00:00Z ┆ EWR    ┆ IAH  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ 2013.0 ┆ 2013-01-01T10:00:00Z ┆ LGA    ┆ IAH  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ 2013.0 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ MIA  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ 2013.0 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ BQN  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ 2013.0 ┆ 2013-01-01T11:00:00Z ┆ LGA    ┆ ATL  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ …      ┆ …                    ┆ …      ┆ …    ┆ … ┆ …       ┆ …     ┆ …     ┆ …      │
│ 2013.0 ┆ 2013-09-30T18:00:00Z ┆ JFK    ┆ DCA  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ 2013.0 ┆ 2013-10-01T02:00:00Z ┆ LGA    ┆ SYR  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ 2013.0 ┆ 2013-09-30T16:00:00Z ┆ LGA    ┆ BNA  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ 2013.0 ┆ 2013-09-30T15:00:00Z ┆ LGA    ┆ CLE  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
│ 2013.0 ┆ 2013-09-30T12:00:00Z ┆ LGA    ┆ RDU  ┆ … ┆ null    ┆ null  ┆ null  ┆ null   │
└────────┴──────────────────────┴────────┴──────┴───┴─────────┴───────┴───────┴────────┘

In [20]:
from hea.tidy import join_by
flights2.left_join(planes, join_by("tailnum"))

shape: (336_776, 14)
┌────────┬──────────────────────┬────────┬──────┬───┬─────────┬───────┬───────┬───────────┐
│ year.x ┆ time_hour            ┆ origin ┆ dest ┆ … ┆ engines ┆ seats ┆ speed ┆ engine    │
│ ---    ┆ ---                  ┆ ---    ┆ ---  ┆   ┆ ---     ┆ ---   ┆ ---   ┆ ---       │
│ i64    ┆ str                  ┆ str    ┆ str  ┆   ┆ i64     ┆ i64   ┆ f64   ┆ str       │
╞════════╪══════════════════════╪════════╪══════╪═══╪═════════╪═══════╪═══════╪═══════════╡
│ 2013   ┆ 2013-01-01T10:00:00Z ┆ EWR    ┆ IAH  ┆ … ┆ 2       ┆ 149   ┆ null  ┆ Turbo-fan │
│ 2013   ┆ 2013-01-01T10:00:00Z ┆ LGA    ┆ IAH  ┆ … ┆ 2       ┆ 149   ┆ null  ┆ Turbo-fan │
│ 2013   ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ MIA  ┆ … ┆ 2       ┆ 178   ┆ null  ┆ Turbo-fan │
│ 2013   ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ BQN  ┆ … ┆ 2       ┆ 200   ┆ null  ┆ Turbo-fan │
│ 2013   ┆ 2013-01-01T11:00:00Z ┆ LGA    ┆ ATL  ┆ … ┆ 2       ┆ 178   ┆ null  ┆ Turbo-fan │
│ …      ┆ …                    ┆ …      ┆ …    ┆ … ┆ …       ┆ …     ┆ …     ┆ …         │
│ 2013   ┆ 2013-09-30T18:00:00Z ┆ JFK    ┆ DCA  ┆ … ┆ null    ┆ null  ┆ null  ┆ null      │
│ 2013   ┆ 2013-10-01T02:00:00Z ┆ LGA    ┆ SYR  ┆ … ┆ null    ┆ null  ┆ null  ┆ null      │
│ 2013   ┆ 2013-09-30T16:00:00Z ┆ LGA    ┆ BNA  ┆ … ┆ null    ┆ null  ┆ null  ┆ null      │
│ 2013   ┆ 2013-09-30T15:00:00Z ┆ LGA    ┆ CLE  ┆ … ┆ null    ┆ null  ┆ null  ┆ null      │
│ 2013   ┆ 2013-09-30T12:00:00Z ┆ LGA    ┆ RDU  ┆ … ┆ null    ┆ null  ┆ null  ┆ null      │
└────────┴──────────────────────┴────────┴──────┴───┴─────────┴───────┴───────┴───────────┘

In [21]:
flights2.left_join(airports, join_by(col("dest") == col("faa")))

shape: (336_776, 13)
┌──────┬──────────────────────┬────────┬──────┬───┬──────┬──────┬──────┬──────────────────┐
│ year ┆ time_hour            ┆ origin ┆ dest ┆ … ┆ alt  ┆ tz   ┆ dst  ┆ tzone            │
│ ---  ┆ ---                  ┆ ---    ┆ ---  ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---              │
│ i64  ┆ str                  ┆ str    ┆ str  ┆   ┆ i64  ┆ i64  ┆ str  ┆ str              │
╞══════╪══════════════════════╪════════╪══════╪═══╪══════╪══════╪══════╪══════════════════╡
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ EWR    ┆ IAH  ┆ … ┆ 97   ┆ -6   ┆ A    ┆ America/Chicago  │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ LGA    ┆ IAH  ┆ … ┆ 97   ┆ -6   ┆ A    ┆ America/Chicago  │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ MIA  ┆ … ┆ 8    ┆ -5   ┆ A    ┆ America/New_York │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ BQN  ┆ … ┆ null ┆ null ┆ null ┆ null             │
│ 2013 ┆ 2013-01-01T11:00:00Z ┆ LGA    ┆ ATL  ┆ … ┆ 1026 ┆ -5   ┆ A    ┆ America/New_York │
│ …    ┆ …                    ┆ …      ┆ …    ┆ … ┆ …    ┆ …    ┆ …    ┆ …                │
│ 2013 ┆ 2013-09-30T18:00:00Z ┆ JFK    ┆ DCA  ┆ … ┆ 15   ┆ -5   ┆ A    ┆ America/New_York │
│ 2013 ┆ 2013-10-01T02:00:00Z ┆ LGA    ┆ SYR  ┆ … ┆ 421  ┆ -5   ┆ A    ┆ America/New_York │
│ 2013 ┆ 2013-09-30T16:00:00Z ┆ LGA    ┆ BNA  ┆ … ┆ 599  ┆ -6   ┆ A    ┆ America/Chicago  │
│ 2013 ┆ 2013-09-30T15:00:00Z ┆ LGA    ┆ CLE  ┆ … ┆ 791  ┆ -5   ┆ A    ┆ America/New_York │
│ 2013 ┆ 2013-09-30T12:00:00Z ┆ LGA    ┆ RDU  ┆ … ┆ 435  ┆ -5   ┆ A    ┆ America/New_York │
└──────┴──────────────────────┴────────┴──────┴───┴──────┴──────┴──────┴──────────────────┘

In [22]:
flights2.left_join(airports, join_by(col("origin") == col("faa")))

shape: (336_776, 13)
┌──────┬──────────────────────┬────────┬──────┬───┬─────┬─────┬─────┬──────────────────┐
│ year ┆ time_hour            ┆ origin ┆ dest ┆ … ┆ alt ┆ tz  ┆ dst ┆ tzone            │
│ ---  ┆ ---                  ┆ ---    ┆ ---  ┆   ┆ --- ┆ --- ┆ --- ┆ ---              │
│ i64  ┆ str                  ┆ str    ┆ str  ┆   ┆ i64 ┆ i64 ┆ str ┆ str              │
╞══════╪══════════════════════╪════════╪══════╪═══╪═════╪═════╪═════╪══════════════════╡
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ EWR    ┆ IAH  ┆ … ┆ 18  ┆ -5  ┆ A   ┆ America/New_York │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ LGA    ┆ IAH  ┆ … ┆ 22  ┆ -5  ┆ A   ┆ America/New_York │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ MIA  ┆ … ┆ 13  ┆ -5  ┆ A   ┆ America/New_York │
│ 2013 ┆ 2013-01-01T10:00:00Z ┆ JFK    ┆ BQN  ┆ … ┆ 13  ┆ -5  ┆ A   ┆ America/New_York │
│ 2013 ┆ 2013-01-01T11:00:00Z ┆ LGA    ┆ ATL  ┆ … ┆ 22  ┆ -5  ┆ A   ┆ America/New_York │
│ …    ┆ …                    ┆ …      ┆ …    ┆ … ┆ …   ┆ …   ┆ …   ┆ …                │
│ 2013 ┆ 2013-09-30T18:00:00Z ┆ JFK    ┆ DCA  ┆ … ┆ 13  ┆ -5  ┆ A   ┆ America/New_York │
│ 2013 ┆ 2013-10-01T02:00:00Z ┆ LGA    ┆ SYR  ┆ … ┆ 22  ┆ -5  ┆ A   ┆ America/New_York │
│ 2013 ┆ 2013-09-30T16:00:00Z ┆ LGA    ┆ BNA  ┆ … ┆ 22  ┆ -5  ┆ A   ┆ America/New_York │
│ 2013 ┆ 2013-09-30T15:00:00Z ┆ LGA    ┆ CLE  ┆ … ┆ 22  ┆ -5  ┆ A   ┆ America/New_York │
│ 2013 ┆ 2013-09-30T12:00:00Z ┆ LGA    ┆ RDU  ┆ … ┆ 22  ┆ -5  ┆ A   ┆ America/New_York │
└──────┴──────────────────────┴────────┴──────┴───┴─────┴─────┴─────┴──────────────────┘

In [23]:
airports.semi_join(flights2, join_by(col("faa") == col("origin")))

shape: (3, 8)
┌─────┬─────────────────────┬───────────┬────────────┬─────┬─────┬─────┬──────────────────┐
│ faa ┆ name                ┆ lat       ┆ lon        ┆ alt ┆ tz  ┆ dst ┆ tzone            │
│ --- ┆ ---                 ┆ ---       ┆ ---        ┆ --- ┆ --- ┆ --- ┆ ---              │
│ str ┆ str                 ┆ f64       ┆ f64        ┆ i64 ┆ i64 ┆ str ┆ str              │
╞═════╪═════════════════════╪═══════════╪════════════╪═════╪═════╪═════╪══════════════════╡
│ EWR ┆ Newark Liberty Intl ┆ 40.6925   ┆ -74.168667 ┆ 18  ┆ -5  ┆ A   ┆ America/New_York │
│ JFK ┆ John F Kennedy Intl ┆ 40.639751 ┆ -73.778925 ┆ 13  ┆ -5  ┆ A   ┆ America/New_York │
│ LGA ┆ La Guardia          ┆ 40.777245 ┆ -73.872608 ┆ 22  ┆ -5  ┆ A   ┆ America/New_York │
└─────┴─────────────────────┴───────────┴────────────┴─────┴─────┴─────┴──────────────────┘

In [24]:
airports.semi_join(flights2, join_by(col("faa") == col("dest")))

shape: (101, 8)
┌─────┬───────────────────────────┬───────────┬─────────────┬──────┬─────┬─────┬───────────────────┐
│ faa ┆ name                      ┆ lat       ┆ lon         ┆ alt  ┆ tz  ┆ dst ┆ tzone             │
│ --- ┆ ---                       ┆ ---       ┆ ---         ┆ ---  ┆ --- ┆ --- ┆ ---               │
│ str ┆ str                       ┆ f64       ┆ f64         ┆ i64  ┆ i64 ┆ str ┆ str               │
╞═════╪═══════════════════════════╪═══════════╪═════════════╪══════╪═════╪═════╪═══════════════════╡
│ ABQ ┆ Albuquerque International ┆ 35.040222 ┆ -106.609194 ┆ 5355 ┆ -7  ┆ A   ┆ America/Denver    │
│     ┆ Sunp…                     ┆           ┆             ┆      ┆     ┆     ┆                   │
│ ACK ┆ Nantucket Mem             ┆ 41.253053 ┆ -70.060181  ┆ 48   ┆ -5  ┆ A   ┆ America/New_York  │
│ ALB ┆ Albany Intl               ┆ 42.748267 ┆ -73.801692  ┆ 285  ┆ -5  ┆ A   ┆ America/New_York  │
│ ANC ┆ Ted Stevens Anchorage     ┆ 61.174361 ┆ -149.996361 ┆ 152  ┆ -9  ┆ A   ┆ America/Anchorage │
│     ┆ Intl                      ┆           ┆             ┆      ┆     ┆     ┆                   │
│ ATL ┆ Hartsfield Jackson        ┆ 33.636719 ┆ -84.428067  ┆ 1026 ┆ -5  ┆ A   ┆ America/New_York  │
│     ┆ Atlanta Int…              ┆           ┆             ┆      ┆     ┆     ┆                   │
│ …   ┆ …                         ┆ …         ┆ …           ┆ …    ┆ …   ┆ …   ┆ …                 │
│ TPA ┆ Tampa Intl                ┆ 27.975472 ┆ -82.53325   ┆ 26   ┆ -5  ┆ A   ┆ America/New_York  │
│ TUL ┆ Tulsa Intl                ┆ 36.198389 ┆ -95.888111  ┆ 677  ┆ -6  ┆ A   ┆ America/Chicago   │
│ TVC ┆ Cherry Capital Airport    ┆ 44.741445 ┆ -85.582235  ┆ 624  ┆ -5  ┆ A   ┆ America/New_York  │
│ TYS ┆ Mc Ghee Tyson             ┆ 35.810972 ┆ -83.994028  ┆ 981  ┆ -5  ┆ A   ┆ America/New_York  │
│ XNA ┆ NW Arkansas Regional      ┆ 36.281869 ┆ -94.306811  ┆ 1287 ┆ -6  ┆ A   ┆ America/Chicago   │
└─────┴───────────────────────────┴───────────┴─────────────┴──────┴─────┴─────┴───────────────────┘

In [25]:
flights2.anti_join(airports, join_by(col("dest") == col("faa"))).distinct("dest")

shape: (4, 1)
┌──────┐
│ dest │
│ ---  │
│ str  │
╞══════╡
│ BQN  │
│ SJU  │
│ STT  │
│ PSE  │
└──────┘

In [26]:
flights2.anti_join(planes, join_by("tailnum")).distinct("tailnum")

shape: (722, 1)
┌─────────┐
│ tailnum │
│ ---     │
│ str     │
╞═════════╡
│ N3ALAA  │
│ N3DUAA  │
│ N542MQ  │
│ N730MQ  │
│ N9EAMQ  │
│ …       │
│ N823MQ  │
│ N5FCAA  │
│ N5ERAA  │
│ N654MQ  │
│ N647MQ  │
└─────────┘

In [27]:
from hea import session_info
session_info()

Python version 3.13.11 (CPython)
Platform: arm64-darwin25.4.0
Running under: macOS 26.4.1

BLAS:   accelerate
LAPACK: accelerate

locale: C.UTF-8

time zone: CEST

hea version 0.1.3

attached packages:
[1] IPython_9.13.0    hea_0.1.3         matplotlib_3.10.9 numpy_2.4.4
[5] pandas_3.0.2      polars_1.40.1     pyarrow_24.0.0    pytest_9.0.3
[9] scipy_1.17.1

loaded via a namespace (and not attached):
 [1] PIL_12.2.0            appnope_0.1.4         argparse_1.1
 [4] asttokens_3.0.1       comm_0.2.3            csv_1.0
 [7] ctypes_1.1.0          cycler_0.12.1         dateutil_2.9.0.post0
[10] debugpy_1.8.20        decimal_1.70          decorator_5.2.1
[13] defusedxml_0.7.1      executing_2.2.1       ipaddress_1.0
[16] ipykernel_7.2.0       jedi_0.19.2           json_2.0.9
[19] jupyter_client_8.8.0  jupyter_core_5.9.1    kiwisolver_1.5.0
[22] logging_0.5.1.2       packaging_26.2        parso_0.8.6
[25] platform_1.0.8        platformdirs_4.9.6    prompt_toolkit_3.0.52
[28] psutil_7.2.2          pure_eval_0.2.3       pydevd_3.2.3
[31] pygments_2.20.0       pyparsing_3.3.2       rdatasets_0.2.10
[34] re_2.2.1              six_1.17.0            sksparse_0.5.0
[37] socketserver_0.4      stack_data_0.6.3      tornado_6.5.5
[40] traitlets_5.14.3      wcwidth_0.6.0         zlib_1.0
[43] zmq_27.1.0