In [1]:
import hea
from hea import data, lm, lme

In [2]:
gpa = data("gpa", package="m-clark")
gpa.head()

shape: (5, 10)
┌─────────┬───────────────────┬─────┬─────────┬───┬──────────┬──────┬──────────┬──────────┐
│ student ┆ occas             ┆ gpa ┆ job     ┆ … ┆ admitted ┆ year ┆ semester ┆ occasion │
│ ---     ┆ ---               ┆ --- ┆ ---     ┆   ┆ ---      ┆ ---  ┆ ---      ┆ ---      │
│ i64     ┆ str               ┆ f64 ┆ str     ┆   ┆ str      ┆ i64  ┆ i64      ┆ i64      │
╞═════════╪═══════════════════╪═════╪═════════╪═══╪══════════╪══════╪══════════╪══════════╡
│ 1       ┆ year 1 semester 1 ┆ 2.3 ┆ 2 hours ┆ … ┆ yes      ┆ 1    ┆ 1        ┆ 0        │
│ 1       ┆ year 1 semester 2 ┆ 2.1 ┆ 2 hours ┆ … ┆ yes      ┆ 1    ┆ 2        ┆ 1        │
│ 1       ┆ year 2 semester 1 ┆ 3.0 ┆ 2 hours ┆ … ┆ yes      ┆ 2    ┆ 1        ┆ 2        │
│ 1       ┆ year 2 semester 2 ┆ 3.0 ┆ 2 hours ┆ … ┆ yes      ┆ 2    ┆ 2        ┆ 3        │
│ 1       ┆ year 3 semester 1 ┆ 3.0 ┆ 2 hours ┆ … ┆ yes      ┆ 3    ┆ 1        ┆ 4        │
└─────────┴───────────────────┴─────┴─────────┴───┴──────────┴──────┴──────────┴──────────┘

In [3]:
gpa_lm = lm("gpa ~ occasion", data = gpa)
gpa_lm.summary()

Formula: gpa ~ occasion

Residuals:
     Min       1Q   Median      3Q     Max
-0.90553 -0.22447 -0.01184 0.26921 1.19447

Coefficients:
             Estimate  Std. Error  CI[2.5%]  CI[97.5]%  t value  Pr(>|t|)
(Intercept)  2.599214    0.017846   2.56420    2.63423   145.65    <2e-16  ***
occasion     0.106314    0.005894   0.09475    0.11788    18.04    <2e-16  ***
---
Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

n = 1200, p = 2, Residual SE = 0.349 on 1198 DF
R-Squared = 0.2136, adjusted R-Squared = 0.2129
F-statistics = 325.3394 on 1 and 1198 DF, p-value: 1.573827e-64

Log Likelihood = -437.4883, AIC = 880.9766, BIC = 896.2468

In [4]:
gpa_mixed = lme("gpa ~ occasion + (1 | student)", data = gpa)
gpa_mixed.summary()

Linear mixed model fit by REML
Formula: gpa ~ occasion + (1 | student)

REML criterion at convergence: 408.8929

Scaled residuals:
    Min      1Q  Median     3Q    Max
-3.6169 -0.6373 -0.0004 0.6361 2.8310

Random effects:
 Groups   Name        Variance Std.Dev.
 student  (Intercept) 0.06372  0.2524
 Residual             0.05809  0.2410
Number of obs: 1200, groups:  student, 200

Fixed effects:
             Estimate  Std. Error  t value
(Intercept)  2.599214    0.021696   119.80
occasion     0.106314    0.004074    26.10

Correlation of Fixed Effects:
         (Intr)
occasion -0.469

In [5]:
gpa_mixed.confint()

shape: (4, 3)
┌─────────────┬──────────┬──────────┐
│ parameter   ┆ 2.5%     ┆ 97.5%    │
│ ---         ┆ ---      ┆ ---      │
│ str         ┆ f64      ┆ f64      │
╞═════════════╪══════════╪══════════╡
│ .sig01      ┆ 0.225174 ┆ 0.28246  │
│ .sigma      ┆ 0.230711 ┆ 0.251851 │
│ (Intercept) ┆ 2.556651 ┆ 2.641777 │
│ occasion    ┆ 0.098326 ┆ 0.114303 │
└─────────────┴──────────┴──────────┘

In [6]:
gpa_mixed.ranef['student'].head(5)

shape: (5, 2)
┌─────────┬─────────────┐
│ student ┆ (Intercept) │
│ ---     ┆ ---         │
│ i64     ┆ f64         │
╞═════════╪═════════════╡
│ 1       ┆ -0.070895   │
│ 2       ┆ -0.215578   │
│ 3       ┆ 0.088257    │
│ 4       ┆ -0.186642   │
│ 5       ┆ 0.030384    │
└─────────┴─────────────┘

In [7]:
gpa_mixed.predict()

shape: (1_200, 1)
┌──────────┐
│ fit      │
│ ---      │
│ f64      │
╞══════════╡
│ 2.528319 │
│ 2.634634 │
│ 2.740948 │
│ 2.847262 │
│ 2.953577 │
│ …        │
│ 3.054216 │
│ 3.16053  │
│ 3.266844 │
│ 3.373159 │
│ 3.479473 │
└──────────┘

In [19]:
hea.DataFrame({
    "lm": gpa_lm.predict(), 
    "lme w/o re": gpa_mixed.predict(re_form=False),
    "lme w/ re": gpa_mixed.predict(),
})

shape: (1_200, 3)
┌──────────┬────────────┬───────────┐
│ lm       ┆ lme w/o re ┆ lme w/ re │
│ ---      ┆ ---        ┆ ---       │
│ f64      ┆ f64        ┆ f64       │
╞══════════╪════════════╪═══════════╡
│ 2.599214 ┆ 2.599214   ┆ 2.528319  │
│ 2.705529 ┆ 2.705529   ┆ 2.634634  │
│ 2.811843 ┆ 2.811843   ┆ 2.740948  │
│ 2.918157 ┆ 2.918157   ┆ 2.847262  │
│ 3.024471 ┆ 3.024471   ┆ 2.953577  │
│ …        ┆ …          ┆ …         │
│ 2.705529 ┆ 2.705529   ┆ 3.054216  │
│ 2.811843 ┆ 2.811843   ┆ 3.16053   │
│ 2.918157 ┆ 2.918157   ┆ 3.266844  │
│ 3.024471 ┆ 3.024471   ┆ 3.373159  │
│ 3.130786 ┆ 3.130786   ┆ 3.479473  │
└──────────┴────────────┴───────────┘

In [10]:
gpa_lm.predict()

shape: (1_200, 1)
┌──────────┐
│ fit      │
│ ---      │
│ f64      │
╞══════════╡
│ 2.599214 │
│ 2.705529 │
│ 2.811843 │
│ 2.918157 │
│ 3.024471 │
│ …        │
│ 2.705529 │
│ 2.811843 │
│ 2.918157 │
│ 3.024471 │
│ 3.130786 │
└──────────┘

In [11]:
gpa_mixed

Linear mixed model fit by REML
Formula: gpa ~ occasion + (1 | student)
REML criterion at convergence: 408.8929
Random effects:
 Groups   Name        Std.Dev.
 student  (Intercept) 0.2524
 Residual             0.2410
Number of obs: 1200, groups:  student, 200
Fixed Effects:
(Intercept)  occasion
   2.599214  0.106314